kind: Service
apiVersion: v1
metadata:
  name: java-app
  labels:
    name: java-app
spec:
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: java-app
  type: NodePort